#
# Warming up for the application to live as a Google K8s workload
# Docker image will need to live on Google Artifact Registry
#


all:
	@echo "Not sure - see other targets"

registry-auth:
	gcloud auth configure-docker us-west1-docker.pkg.dev


